quackduck/devzat

devchat.go

Let me know if I screwed anything up here. I don't know Go so I'm not entirely familiar with language specific patterns I may or may not have violated.

Modularised a few things

---

.gitignore

I still need to work out how to get the user IP so atm I'm banning based on the user id.

Implement bans based on user id

---

devchat.go

```
tommy: do you mind if i make a secret command?
ishan: sure, go ahead
ishan: you
ishan: will make a pr?
tommy: its super h4x0ry
ishan: hahah
tommy: I will, maybe
ishan: go for it
tommy: maybe not
ishan: do show me
ishan: I'm intrigued
ishan: 👀
ishan: what will it do
ishan: tell me on slack or smth
tommy: its a secret l33t h4x0r command
ishan: I gotta go
ishan: make a PR!
tommy: ill show u when i have implemented it
tommy: I will
ishan: I would love it
```
Don't look at the code since it's perfect. Just merge and deploy :wink:

Add the secret command from the discussion before.

---

devchat.go

Very simple commit to make nobody spoofs the `devbot` user.

Make sure we don't have anyone called devbot

---

devchat.go

Automate the printing of the board and add numbers to the cell number, so it's easier for the user.
Image of new board: https://i.ibb.co/xGF5pnS/pic-selected-210519-2033-34.png
I also added this message, so the user knows what to do.
> devbot: To make your move type /tic <move>

Make tic-tac-toe interface cleaner

---

devchat.go

restructured u.color and color management to encourage easier special color adding

adding rainbow as secret color

---

devchat.go

I think the title of this PR is explanatory enough. Not entirely certain if it'll work, but I'm guessing it should!

Add ./name as an alternative to ./nick

---

devchat.go

Basically a fix to this: [https://github.com/quackduck/devzat/pull/26#issuecomment-857888574](https://github.com/quackduck/devzat/pull/26#issuecomment-857888574)

Make UI better for letting users know their word isn't being shown.

---

commands.go

Is this bad code? Yes. Does it work? Probably, works for me atleast.
Just clears your screen, nothing special.

Clear command

---

devchat.go

A small anti-spam system which triggers when someone sends 10 messages in one second. Doubt it would take down ./color random spamming but if it does its just to tweak the max messages per second value.
Just to take down spambots if someone decides to spam it

Anti-Spambot

---

commands.go
devchat.go

Continutation from #29. basically just lets you private message someone by doing ./room @<mention> and ./room to leave to the previous room

Toggling only talking to private messages

---

devchat.go

As user Cole mentioned, the prompt asking for a new username was very aggressive and not very insightful.

Improved username prompt.

---

README.md

Some users might be unhappy about logging in and having their real name showed to everyone.
To prevent this, I told in the readme how to log in with a nickname.

Documented loggin with nickname in README

---

commands.go
devchat.go

Added option to display time in 24h format.

24h format

---

README.md

Used space instead of tabs in readme.
I made a mistake in the last PR about the readme, sorry.

Fixed indent.

---

twitter.go

The acces to the function connecting
to Twitter is protected by a lock.
This prevent the bot to send a myriad
of messages when peoples connect and
deconect very quickely.

Preventing devbot to spam Twitter.

---

commands.go

This command let use see your current
room. This is usefull as the users
command no longuer does it.

Added a pwd command.

---

devchat.go

When the name is invalid, it tells why.

Improved yet an other time the nick promp.

---

README.md

As some people where kicked out by the pub key auth. I mentioned it and how to deal with it in the README.

Spoke about plublic key in the README.

---

colors.go
devchat.go

It is possible to reset one's background
and to combine a special color and a
background.

Improved background handling.

---

devchat.go

When a user left a room where they were alone in, the room was lest open.
This PR fixes that and ensure that there is no empty rooms.

Clears empty rooms

---

colors.go
commands.go
devchat.go

This adds the command `pronouns`, which allows you to both declare your pronouns and to set your own pronouns.
Example usage:
pronouns she her hers
pronouns xey xem
pronouns he they
pronouns @duck

Add support to display pronouns

---

commands.go
devchat.go
slack.go
twitter.go

This commit makes it so that we can access bans in O(1) constant time.
It also allows the program to run if the twitter or slack files are not found.

Don't panic on file not found.

---

devchat.go

As there is a lot of new user, this might add some DoS protection.

Added way to limit the size of messages at compile time.

---

main.go
util.go

Hi, i've found the valentines function (very funny), i decided to extends them with holidays check.
This func check find a match with month - day and write a image.
I know this commit it's only for fun, but after all doesn't exist only Valentine's day <3

Add holidays func

---

main.go
rpc.go

See https://github.com/Merlin04/devzat-hc-emoji for plugin implementation of functionality

Remove HC Slack emoji integration, fix bug with regex impl

---

censor.go
util.go

As we talked about, I move what you made with go-away in a separate file. Once you merge this into main, I will do the same in the rustrict branch.

Moved all censor-related functions in a separate file.

---

commands.go

This should help build the Unix hacker feel of
Devzat and please my personal muscle memory.

Use :q as an alias for exit.

---

commands.go

This will help terminal notice that this is a
link that could be clicked.

Add https:// before address of the line remover.

---

main.go

That way, all commands can use a @<name> properly.

=@<name> to send DMs can be autocompleted.

---

commands.go
main.go
util.go

As we have some inactive users with white-space names, having commands that can use IDs instead of names is quite valuable.

Improve admins command

---

main.go

In the bridges, the user names are quite hard to read. Making them bold would make using the bridges more pleasant.

Bold the user names in bridges.

---

commands.go
util.go

Devbot no longer let user bully it.

---

main.go

This will prevent the main chat to be stuck
because of a limitation of an external API.

Discard message to bridge if the channels are full

---

colors.go

color elitedino

---

commands.go

Because my fingers are faster than my Brain :)

Add :wq as an alias of exit

---

colors.go
commands.go
main.go

If you want to play with it a bit before giving further info.

User-customizable prompts

---

colors.go

The first letter was a bit too green.

Improve the sunset color scheme.

---

go.mod
go.sum
main.go
util.go

It is quite painful to self-host Devzat as the server crashes when it does not find some needed files such as the private key and the ban list.
This PR generates those files when needed.

Better install

---

devzatapi/main.go
discord.go
go.mod
go.sum

This can be merged as soon as the discord library updates their release to include this commit:
https://github.com/bwmarrin/discordgo/commit/e39e715086d29a241ea3667713764c377c0b15b0

New discord usernames

---

commands.go

devbot improvements

---

commands.go

This will create a function so when a user types 8ball (input) it will generate a response from a predefined list of answers.

Add Magic8Ball Function

---

mainserver.yml

:smile-with-7-parentheses-no-more-no-less:

make myself an admin

---

commands.go

the new format will display the username + reason for being banned

Add Ban_Reason to ban function

---

mainserver.yml

Add new computer ID to mainserver.yml

---

commands.go

As suggested in #224, here is a command to delete an empty room.

Add rmdir command.

---

README.md

The info is not really clear as showed by multiple new users being called 'nickname' each time Devzat is advertised in a new place.

Clarify the nickname documentation

---

util.go

de-elonize

---

go.mod
go.sum

Update discord module.
