- README.md
- commands.go
I synced the message output when using ./help and also the text in README.md to read the same line for direct messaging. At `devzat.hackclub.com` it still reads the wrong output for dm when you use `./help`:
```
c1sc0: ./help
Welcome to Devzat! Devzat is chat over SSH: github.com/quackduck/devzat
Because there's SSH apps on all platforms, even on mobile, you can join from anywhere.
Interesting features:
• Many, many commands. Run ./commands.
• Rooms! Run ./room to see all rooms and use ./room #foo to join a new room.
• Markdown support! Tables, headers, italics and everything. Just use \n in place of newlines.
• Code syntax highlighting. Use Markdown fences to send code. Run ./example-code to see an example.
• Direct messages! Send a quick DM using ./@user <msg> or stay in DMs by running …
```
> fixed the help message in ./help command

- twitter.go
So this way it makes the link openable from terminal. Let's say you are using `gnome-terminal` like I do on linux, and you right click that link you will get a `open in browser`. This way you can actually directly open that link without needing to copy paste it.
> added https:// to twitter url, makes it aktually openable from terminal

- commands.go
The cat function does the parsing for the
README argument.
> Fixed the 'cat README.md' command.

- devchat.go
Sometime, especialy with small terminals
and fancy name colors, the last printed
messages was deleted because the colored
char were counted in the printed message
size. This is now fixed.
> Fixed deletion of messages on client.

- commands.go
- devchat.go
Sometime, users were ping while
their bell was off or for every
messages while their bell were
on default mode. This is fixed.
> Fixed bugs with the bell.

- README.md
The was still the old './cmds'.
> Fixed command prefix in README.

- commands.go
- devchat.go
- util.go
Since IP's can change, it's better if we get the ID from the public key. This has a few benefits, such as:
* People in the same network/household will be able to connect to the chat even if one person is banned.
* Admin takeover is much harder since instead of needing to be in the same network, you will need their public/private key pair.
* A person can connect from anywhere and as long as they have their key they can prove their legitimacy. (i.e. a random person called "ishan" on the chat won't be able to act the real ishan since your ID will be static and thus the fake ishan will be detected).
In the case that a user logged in without using their key pair, we will still get their ID from the IP, but we still gain all the benefits of pubkey authentication.
> Generate the user ID based on their public key instead of IP

- colors.go
When the color had no red, the converted
number was 2 char longs which made the
rest of the getStyle function unable to parse
it. Changing Atoa to Sprintf means that I can
enforce to have leading 0 when the number is
only two digit long, which mean that it will
be parsed correctly.
> Fixed bug with color random.

- commands.go
If there was a capitalized letter in the
username, the command failed to find them.
> Fixed finding user's pronouns.

- colors.go
This adds pride flags as colors you can set, like `color rainbow`.
Some of them include:
- lesbian
- bisexual
- gay
- trans
- asexual﻿
> Add pride flag colors

- commands.go
- util.go
This add some of the fixes suggested in #89.
A `admins` command list all admins.
When listing users in room, admins have a star before their names.
> Admin flair

- commands.go
This PR fixes the escaping of the `shrug` command's shrug emoji, such that it renders properly when used both in docs and the client.
> [bug] Fix shrug markdown escaping

- commands.go
- devchat.go
When a user changed their nick to an already used
nick, there was no info for the other users to
see the final name they choosen.
> Devbot notify about users changing nicknames.

- commands.go
This is meant to help terminal recognize
that it is an hyperlink.
> Added https prefix before the emojis link.

- devchat.go
Sharing a single variable between multiple goroutines with no synchronization should generally be avoided
> Don't share error between multiple goroutines

- mainserver.yml
The key I used before is apparently no longer accepted by devzat, so I generated a new one that does work.
> Update my key id.

- Admin's Manual.md
- config.go
- main.go
One user wanted to have a private chat with Devzat. I made so that this can optionally be made.
> Private chat

- main.go
- util.go
This let us use the autocomplete in commands such as bio, pronouns, or DMs.
Names can no longer start with '@' to ensure no ambiguity.
> Enable the use of @<name> in commands.

- main.go
There used to be no spaces between the user name
and the message, which was kind of awkward.
> Fix message when user is disconnected in case of an error.

- discord.go
If messages take too long to be sent, the channel
switch to compact mode. It stays that way until
all messages have been transmitted.
> Switch to Discord compact mode during overloading

- rpc.go
There is two issues with the current implementation of `lstoken`.
* The first token is numbered '2'.
* The numbers are not 0 padded which cause the column to be misaligned which hurts the Feng Shui of the output.
This PR fixes those two issues.
> Fix lstokens command

- commands.go
- main.go
The current use of middleware had two issue:
* As the message was processed before we check if the message is a DM, middleware admin could snoop on any DM. This is not great for privacy.
* Bridge messages didn't go though middleware. On a first thought, this might have been seen as a good thing considering this reduce the difference between what is on the bridge and what is on the SSH interface. But there is already a lot of difference between messages sent on bridges and how the appear on the SSH interface. Messages can be edited on bridges, custom emotes are used there, and go-away censor the messages from bridges.
> Move the invocation of middleware

- commands.go
When I attempted to use "prompt" in the past, it hid my username so I could only see it after I sent a message.
> Add Dialogue to PromptCMD

- main.go
Use of `err := <...>` while err is already defined prevents compilation on go 1.19.
> Fix an assignment to err

- README-CN.md
- README.md
#235 
Add Chinese translation for README.md, the file is README-CN.md.
Updating help related to the nick and kick commands.
Not sure how to include a link to README-CN.md in README.md, do I need to commit this branch first and then reference it via markdown later?
> #issue 235 ->Add Chinese translation

- main.go
The error handling for when not being able to get the TOR IP list was broken, resulting in a crash as shown in #246.
> Recover from not being able to read TOR IPs.

- commands.go
When an user uses "clear" to refresh their screens, it's not displayed to other users. This is to reduce the noise during discussions.
> `clear` command is not displayed to other users.

- commands.go
- devzat_test.go
- main.go
- util.go
This PR adds the following improvement related to bans:
* Temporary bans are robust against server restart.
* User banned temporary can see how long they have to wait.
* Cleaner in-code ban API.
* Devbot banning and anti-spam banning are respectively one minute and one month instead of being forever.
> Better bans
